services:
  database:
    build: database
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./database/sql:/var/lib/postgres/data
  web:
    build: web
    user: "node"
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./web:/home/node/app
